Repository speaq-ai/react-ui, pull requests merged in 2019-10, with the labels that each got.

#23 Maintaining State On Actions.
  src/components/chat/index.js
Labels: enhancement

#30 Added Filter Everything Functionality
  src/components/chat/index.js
Labels: bug, enhancement

#25 added tts functionality and various UI tweaks to accommodate
  package.json
  src/components/chat/chat.test.js
  src/components/chat/index.js
  src/components/common/floating-button.js
  src/components/visualizer/index.js
  src/ducks/index.js
  src/utils/speaq-api.js
  webpack.config.js
  yarn.lock
Labels: enhancement, frontend

#36 Cunningham osm
  src/components/chat/index.js
Labels: enhancement

#44 Required Dataset for Change View
  src/components/chat/index.js
Labels: enhancement, watson

#45 UI Refactor
  src/components/chat/action-processor.js
  src/components/chat/index.js
  src/components/common/floating-button.js
  src/components/login/private-route.js
  src/components/visualizer/index.js
  src/containers/app.js
  src/containers/visualizer.js
  src/utils/audio.js
Labels: documentation
